#<font color='blue' size='5px'/> Pytorch Overview<font/>

# 1 Introduction

To consider yourself proficient in PyTorch and become an expert in this deep learning framework, you should cover a range of topics and gain hands-on experience in the following areas:

1. **Basics of PyTorch**:
   - Understand what tensors are and how they work as the fundamental data structure in PyTorch.
   - Learn about tensor operations, such as indexing, slicing, reshaping, and mathematical operations.

![image](https://www.cc.gatech.edu/~san37/img/dl/tensor.png)

2. **Data Handling**:
   - Master PyTorch's data loading utilities, such as DataLoader, Dataset, and transforms.
   - Preprocess and augment datasets for training.
   - Handle various data formats like images, text, and sequences.

3. **Creating Models and Training Neural Networks**:
   - Build neural network models using PyTorch's nn.Module class.
   - Define custom layers and modules to create complex architectures.
   - Explore different activation functions, loss functions, and optimizers available in PyTorch.
   - Implement custom training loops for your models, including forward and backward passes.
   - Study gradient descent optimization techniques, learning rates, and weight initialization strategies.
   - Learn about regularization techniques like dropout and weight decay.

  **To create & Train a model with PyTorch, you need to follow these steps:**
  1. Import the necessary libraries:
  ```python
  import torch
  import torch.nn as nn
  import torch.optim as optim
  ```

  2. Define your model class by inheriting from `nn.Module`:
  ```python
  class YourModel(nn.Module):
      def __init__(self, input_size, hidden_size, output_size):
          super(YourModel, self).__init__()
          self.hidden = nn.Linear(input_size, hidden_size)
          self.relu = nn.ReLU()
          self.output = nn.Linear(hidden_size, output_size)

      def forward(self, x):
          x = self.hidden(x)
          x = self.relu(x)
          x = self.output(x)
          return x
  ```

  3. Instantiate your model with the desired input, hidden, and output sizes:
  ```python
  input_size = 100
  hidden_size = 50
  output_size = 10
  model = YourModel(input_size, hidden_size, output_size)
  ```

  4. Define your loss function and optimizer:
  ```python
  criterion = nn.CrossEntropyLoss()
  optimizer = optim.SGD(model.parameters(), lr=0.1)
  ```

  5. Train your model by iterating over your dataset:
  ```python
  for inputs, labels in dataloader:
      optimizer.zero_grad()
      outputs = model(inputs)
      loss = criterion(outputs, labels)
      loss.backward()
      optimizer.step()
  ```

  6. Evaluate your model on a separate validation set:
  ```python
  with torch.no_grad():
      model.eval()
      for inputs, labels in validation_dataloader:
          outputs = model(inputs)
          # Perform evaluation metrics calculation
  ```

  7. Save and load your model:
  ```python
  torch.save(model.state_dict(), 'model.pth')
  model = YourModel(input_size, hidden_size, output_size)
  model.load_state_dict(torch.load('model.pth'))
  ```



4. **Model Evaluation and Metrics**:
   - Calculate and interpret performance metrics such as accuracy, precision, recall, and F1-score.
   - Perform model evaluation using validation and test datasets.

5. **Transfer Learning and Pretrained Models**:
   - Understand how to **fine-tune pre-trained models** for specific tasks. Like **YOLO**
   - Explore popular pre-trained models available in PyTorch's **torchvision library**.

   - **PyTorch's DOC:**

   https://pytorch.org/docs/stable/index.html


6. **GPU Acceleration**:
   - Learn how to leverage GPUs for **faster training using CUDA** and PyTorch's GPU support.
   - **Optimize your code for GPU memory** management.



7. **Debugging and Troubleshooting**:
   - Develop debugging skills to identify and resolve common issues in PyTorch code.
   - Handle problems related to vanishing gradients, exploding gradients, and overfitting.

8. **Deployment and Inference**:
   - Deploy PyTorch models to production **environments** using frameworks like **Flask or FastAPI**.
   - Optimize models for **inference on edge devices, mobile devices, or cloud platforms**.

9. **PyTorch Ecosystem**:
    - Explore related libraries and tools like:
      - torchvision,
      - torchaudio,
      - torchtext
    - Stay updated with the latest developments and community contributions.


10. **Deep Learning Research Concepts** (optional):
    - If you plan to contribute to research or work on advanced topics, study concepts like:
      - attention mechanisms,
      - GANs,
      - reinforcement learning,
      - advanced recurrent networks.




11. **Documentation and Community Resources**:
    - Refer to PyTorch documentation and official tutorials regularly.
    - Engage with the PyTorch community through forums, blogs, and social media to learn from others and share your knowledge.


# 2 Tensor Handling

Tensors are a fundamental data structure in PyTorch. They are similar to NumPy arrays, but **they can also be used on GPUs to accelerate computations**. Tensors can be used to represent images, matrices, and other data structures.

Here are some of the ways to deal with tensors in PyTorch:

* **Creating tensors:** There are many ways to create tensors. You can create a tensor from a Python list or tuple, from a NumPy array, or from scratch.
* **Indexing tensors:** You can index tensors just like you would index Python lists or NumPy arrays.
* **Arithmetic operations on tensors:** You can perform all the usual arithmetic operations on tensors, such as addition, subtraction, multiplication, and division.
* **Functions on tensors:** There are many functions available for tensors, such as slicing, reshaping, and transposing.
* **Gradients:** Tensors can be used to compute gradients, which are used in machine learning algorithms to train models.

- **Use the tolist() method:** The tolist() method returns the tensor as a Python list. The elements of the list will be the values of the tensor.

- **Use the numpy() function:** The numpy() function converts the tensor to a NumPy array. NumPy arrays are similar to Python lists, but they have some additional features.

* PyTorch Tensors Tutorial:

  https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html

* PyTorch Tensors Documentation:

  https://pytorch.org/docs/stable/tensors.html

* A Complete Guide to PyTorch Tensors:

  https://www.educba.com/pytorch-tensors/

In [ ]:
import torch

In [ ]:
# Create a tensor from a Python list
tensor=torch.tensor([1,2,3])

# Print the tensor
print(tensor)

tensor([1, 2, 3])


In [ ]:
# Index the tensor
print(tensor[0])


tensor(1)


In [ ]:
# Add two tensors
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])

print(tensor1 + tensor2)

tensor([5, 7, 9])


In [ ]:
# Apply a function to a tensor
print(torch.sin(tensor))

tensor([0.8415, 0.9093, 0.1411])


In [ ]:
def f(x):
  return 2*x + 1

# Create a tensor and set requires_grad=True
x = torch.tensor(1.0, requires_grad=True)

# Calculate the gradient of f(x)
f(x).backward()

# Print the gradient
print(x.grad)

tensor(2.)


In [ ]:
## Fun Calc
def f(x):
  return 2*x + 1
f(tensor)

tensor([3, 5, 7])

In [ ]:
## Tensor to List
tensor = torch.tensor([1, 2, 3])

list_from_tensor = tensor.tolist()

print(list_from_tensor)

[1, 2, 3]


In [ ]:
## Tensor to Numpy array
import numpy as np

tensor = torch.tensor([1, 2, 3])

array_from_tensor = np.array(tensor)

print(array_from_tensor)

[1 2 3]


# 3 Dataloader Pipeline

## Theory Guide

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/drive/1W3cO6RoyjJn7k6NyfxAKkykmdQKnRzmj#scrollTo=WTTwpfbVQxew)


# 4 Create & Train models

## Theory Guide

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://drive.google.com/file/d/1ppifF1GxL5YNTnr8wSoMW2CbJHWnfF9p/view?usp=sharing)


# 5 Model Evaluation and Metrics

## Theory Guide

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://drive.google.com/file/d/1ppifF1GxL5YNTnr8wSoMW2CbJHWnfF9p/view?usp=sharing)


# 6 Transfer Learning - Pretrained Models

## Theory Guide

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://drive.google.com/file/d/1ppifF1GxL5YNTnr8wSoMW2CbJHWnfF9p/view?usp=sharing)


# 7 NN_Architectures

# 8 GPU Acceleration:

# 9 PyTorch Ecosystem

# 10 Projects

#### CIFAR10_Classificaiton

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/drive/1kt__AvdDAL1bVzEgwY1sLjH0N8-c1P0l#scrollTo=CYQhnSDXc1wE)


#### LPR Recognition

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/drive/1fjMYmFdKbH8fcYF5DoP-Xxkh1DXTgDjl)
